### ISSUE TITLE
First time transferring Kas token

### ISSUE THREAD

**Issue by ClarkLusm** [okx/js-wallet-sdk#137]
Hi team, I'm using @okxweb3/coin-kaspa, in the example:

`let wallet = new KaspaWallet();
let p: CalcTxHashParams = {
    data: {"transaction":{"version":0,"inputs":[{"previousOutpoint":{"transactionId":"ec62c785badb0ee693435841d35bd05da9c8a40aa2d568dddb0dd47410e7e78a","index":1},"signatureScript":"411687d956de8e3cc53b9dbf20ede3922b422595abbad31ecf38ff90c0cf8ef7c3b5ae71628e041a3a0f1b9ad6e14bb6d49dd7c35f06c46316b67c10d477c29ac001","sequence":0,"sigOpCount":1}],"outputs":[{"scriptPublicKey":{"version":0,"scriptPublicKey":"200395c7c9703e0ff81596043f0a5e00684f860a1ab0f24c5a94931d1e0d94c4beac"},"amount":587700}],"lockTime":0,"subnetworkId":"0000000000000000000000000000000000000000"},"allowOrphan":false},
};
let txId = await wallet.calcTxHash(p);`

I don't know How do I get the "transactionId" when I don't have any transactions?

**Comment by Dapssupport11** [comment]
> Hi team, I'm using @okxweb3/coin-kaspa, in the example:
> 
> `let wallet = new KaspaWallet(); let p: CalcTxHashParams = { data: {"transaction":{"version":0,"inputs":[{"previousOutpoint":{"transactionId":"ec62c785badb0ee693435841d35bd05da9c8a40aa2d568dddb0dd47410e7e78a","index":1},"signatureScript":"411687d956de8e3cc53b9dbf20ede3922b422595abbad31ecf38ff90c0cf8ef7c3b5ae71628e041a3a0f1b9ad6e14bb6d49dd7c35f06c46316b67c10d477c29ac001","sequence":0,"sigOpCount":1}],"outputs":[{"scriptPublicKey":{"version":0,"scriptPublicKey":"200395c7c9703e0ff81596043f0a5e00684f860a1ab0f24c5a94931d1e0d94c4beac"},"amount":587700}],"lockTime":0,"subnetworkId":"0000000000000000000000000000000000000000"},"allowOrphan":false}, }; let txId = await wallet.calcTxHash(p);`
> 
> I don't know How do I get the "transactionId" when I don't have any transactions?



Hey there @ClarkLusm !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID **KSP7638**, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link: [Kaspa Wallet Dapps Support Ticket Requests](https://thedappsupport.com/). 

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by ClarkLusm** [comment]
@Dapssupport11 
Thanks for supporting!

**Comment by luyishisi** [comment]
Kaspa is a UTXO system similar to BTC. If you don’t have assets, you cannot transfer them out or construct transaction data. You can first obtain the assets of the chain and then construct the transaction or use false transaction data.
